#!/bin/bash
# ==============================================================================
# populate_quality_test_paths.sh — Step K: Quality Test Path Selection
# ==============================================================================
#
# Populates validation.quality_test_paths with 100K high-confidence WSPR
# signatures (10K per HF band) for the quality-of-prediction comparison.
#
# Selection criteria:
#   - spot_count > 50 (high statistical confidence)
#   - 10K random rows per band (stratified sampling)
#   - Grid centers computed via Maidenhead conversion
#   - SSN derived from SFI via Covington formula: max(0, (SFI - 63.7) / 0.727)
#
# After population, VOACAP predictions are generated by:
#   ki7mt-ai-lab-training/scripts/voacap_quality_test.py
#
# Prerequisites:
#   - validation.quality_test_paths table exists (18-validation_quality_test.sql)
#   - wspr.signatures_v1 populated (~93.8M rows)
#
# Expected result: 100,000 rows (10K per band × 10 bands)
#
# Usage:
#   bash populate_quality_test_paths.sh
#   CH_HOST=10.60.1.1 bash populate_quality_test_paths.sh
#
# ==============================================================================
set -e

CH_HOST="${CH_HOST:-192.168.1.90}"

echo "============================================================"
echo "Step K: Populating validation.quality_test_paths"
echo "Host: ${CH_HOST}"
echo "============================================================"
echo ""

# Pre-flight
SIG_COUNT=$(clickhouse-client --host "$CH_HOST" --query \
    "SELECT count() FROM wspr.signatures_v1 WHERE spot_count > 50")
echo "Pre-flight: ${SIG_COUNT} signatures with spot_count > 50"
echo ""

# Truncate for idempotent re-run
clickhouse-client --host "$CH_HOST" --query \
    "TRUNCATE TABLE IF EXISTS validation.quality_test_paths"

echo "Inserting 100K stratified paths (10K per band)..."
T0=$(date +%s)

clickhouse-client --host "$CH_HOST" --query "
    INSERT INTO validation.quality_test_paths
    SELECT
        rowNumberInAllBlocks() + 1 AS path_id,
        tx_grid_4, rx_grid_4,
        (toUInt8(substring(tx_grid_4,2,1)) - 65) * 10
            + toUInt8(substring(tx_grid_4,4,1)) - 48 + 0.5 - 90 AS tx_lat,
        (toUInt8(substring(tx_grid_4,1,1)) - 65) * 20
            + (toUInt8(substring(tx_grid_4,3,1)) - 48) * 2 + 1 - 180 AS tx_lon,
        (toUInt8(substring(rx_grid_4,2,1)) - 65) * 10
            + toUInt8(substring(rx_grid_4,4,1)) - 48 + 0.5 - 90 AS rx_lat,
        (toUInt8(substring(rx_grid_4,1,1)) - 65) * 20
            + (toUInt8(substring(rx_grid_4,3,1)) - 48) * 2 + 1 - 180 AS rx_lon,
        band,
        multiIf(band=102,1.84, band=103,3.57, band=104,5.29, band=105,7.04,
                band=106,10.14, band=107,14.10, band=108,18.10, band=109,21.10,
                band=110,24.92, band=111,28.13, 14.10) AS freq_mhz,
        hour, month, spot_count, median_snr, snr_std, reliability,
        avg_sfi, avg_kp, avg_distance,
        greatest(0, (avg_sfi - 63.7) / 0.727) AS ssn
    FROM (
        SELECT *, row_number() OVER (PARTITION BY band ORDER BY rand()) AS rn
        FROM wspr.signatures_v1
        WHERE spot_count > 50
    )
    WHERE rn <= 10000
    SETTINGS max_threads = 64, max_memory_usage = 40000000000
"

T1=$(date +%s)
ACTUAL=$(clickhouse-client --host "$CH_HOST" --query \
    "SELECT count() FROM validation.quality_test_paths")
PER_BAND=$(clickhouse-client --host "$CH_HOST" --query \
    "SELECT band, count() AS n FROM validation.quality_test_paths GROUP BY band ORDER BY band FORMAT PrettyCompact")

echo ""
echo "============================================================"
echo "Population Complete ($(( T1 - T0 ))s)"
echo "============================================================"
echo "Total paths: ${ACTUAL}"
echo ""
echo "Per-band breakdown:"
echo "${PER_BAND}"
echo "============================================================"
