-- ============================================================================
-- ki7mt-ai-lab-core: CUDA Model Features (Float4 Embeddings)
-- ============================================================================
-- Stores float4 embeddings generated by the CUDA bulk-processor from
-- wspr.spots_raw + solar.indices_raw.
--
-- 4.4B rows (one per WSPR spot with solar coverage), 41 GiB on disk.
-- Populated by: ki7mt-ai-lab-cuda bulk-processor (GPU-accelerated)
--
-- The embedding array encodes [distance_norm, freq_log_norm, solar_quality,
-- propagation_score] as Float32 values.
--
-- Indexes:
--   idx_quality: minmax on embedding[4] (propagation score) for quality filtering
--   idx_kp: minmax on kp_index for storm filtering
-- ============================================================================

CREATE TABLE IF NOT EXISTS wspr.model_features (
    timestamp    DateTime         CODEC(Delta(4), ZSTD(1)),
    tx_grid      FixedString(8)   CODEC(ZSTD(1)),
    rx_grid      FixedString(8)   CODEC(ZSTD(1)),
    frequency    UInt64           CODEC(Delta(8), ZSTD(1)),
    band         Int32            CODEC(ZSTD(1)),
    distance     UInt32           CODEC(Delta(4), ZSTD(1)),
    kp_index     Float32          CODEC(ZSTD(1)),
    xray_flux    Float32          CODEC(ZSTD(1)),
    embedding    Array(Float32)   CODEC(ZSTD(1)),
    computed_at  DateTime DEFAULT now() CODEC(Delta(4), ZSTD(1)),
    INDEX idx_quality embedding[4] TYPE minmax GRANULARITY 4,
    INDEX idx_kp kp_index TYPE minmax GRANULARITY 4
) ENGINE = MergeTree
PARTITION BY toYYYYMM(timestamp)
ORDER BY (band, timestamp, tx_grid, rx_grid)
SETTINGS index_granularity = 8192;
